import { readFile, rm, writeFile } from "node:fs/promises";

const templateDir = new URL("../dist/edge-article-template/", import.meta.url);
const html = await readFile(new URL("index.html", templateDir), "utf8");

await writeFile(
  new URL("../edge/generated-template.js", import.meta.url),
  `// Generated by scripts/build_edge_template.mjs.\nexport const ARTICLE_TEMPLATE = ${JSON.stringify(html)};\n`,
);
await rm(templateDir, { recursive: true, force: true });
